---
title: traceback.TracebackException.from_exception
permalink: /Python/traceback/TracebackException/from_exception/
date: 2021-01-01
key: Python.T.traceback.TracebackException.from_exception
category: python
tags: ['metodo python', 'traceback']
sidebar: 
  nav: python
---

{% include w3api/datos.html clase=site.data.Python.T.traceback.TracebackException.metodos valor="from_exception" %}

## Descripción
{{_dato.description }}

## Sintaxis
~~~python
{{ _dato.sintaxis }}~~~

## Parámetros
* **\***,  {% include w3api/function_param_description.html propiedad=_dato valor="*" %}
* **capture_locals**,  {% include w3api/function_param_description.html propiedad=_dato valor="capture_locals" %}
* **exc**,  {% include w3api/function_param_description.html propiedad=_dato valor="exc" %}
* **limit**,  {% include w3api/function_param_description.html propiedad=_dato valor="limit" %}
* **lookup_lines**,  {% include w3api/function_param_description.html propiedad=_dato valor="lookup_lines" %}

## Clase Padre
[TracebackException](/Python/traceback/TracebackException/)

## Ejemplo
~~~python
{{ _dato.code}}
~~~

## Artículos
<ul>
{%- for _ldc in _dato.ldc -%}
   <li>
       <a href="{{_ldc['url'] }}">{{ _ldc['nombre'] }}</a>
   </li>
{%- endfor -%}
</ul>
